---
name: prolog-language-server
description: A Prolog LSP Server
homepage: https://www.swi-prolog.org/pack/list?p=lsp_server
licenses:
  - BSD-2-Clause
languages:
  - Prolog
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:generic/jamesnvc/lsp_server@v2.2.11
  build:
    - target: unix
      bin:
        script: lsp_server/start.sh
      share: |
        swipl pack install https://github.com/jamesnvc/lsp_server/archive/refs/tags/{{VERSION}}.zip --dir="$PWD" -y
        echo 'cd $(dirname "$0"); swipl -g "use_module(library(lsp_server))" -g "lsp_server:main" -t halt -- stdio' > "{{source.build.bin.script}}"
        chmod +x "{{source.build.bin.script}}"
      staged: false
      env:
        VERSION: "{{version}}"

share:
  prolog-language-server: "{{source.build.bin.script}}"
